apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: weather
  name: weather
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: weather
    spec:
      containers:
      - image: cloud-fundamentals_weather
        name: weather
        resources: {}
      restartPolicy: Always
status: {}
